[Interface]
Address = 10.10.10.1/24
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE
ListenPort = 51820
PrivateKey = wIQ35nRmf3dUBXdn864OMZh3dK6gsLUqrXSwI+KZEkw=

[Peer]
PublicKey = MzeqrUWkSBuHEs1jG5u6io665zzAiVOb0KDexkbMji4=
AllowedIPs = 10.10.10.2/32
Endpoint = 177.241.54.83:10558

[Peer]
PublicKey = 1jEGvVWHzCxcF+dxDvfU8RgPisgP5K+VCe2bvh9qqyc=
AllowedIPs = 10.10.10.3/32
Endpoint = 187.188.64.60:57196

[Peer]
PublicKey = 1OOg58MT4lS8z4Ixpm++0eYWvcuV0p/d44i1uDkDsEY=
AllowedIPs = 10.10.10.4/32
Endpoint = 177.231.15.207:4339
