services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot_coordinator
    network_mode: "host"
    command: ["./coordinator"]
    restart: unless-stopped

  edge-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot_edge_1
    network_mode: "host"
    command: ["./edge"]
    restart: unless-stopped
    depends_on:
      - coordinator

  sensor-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot_sensor_1
    network_mode: "host"
    command: ["./sensor"]
    restart: unless-stopped
    depends_on:
      - edge-1